Public Class Form24
    Dim X, Y As Integer
    Dim NewPoint As New System.Drawing.Point
    Dim drag As Boolean
    Dim mousex As Integer
    Dim mousey As Integer
    Private Sub Form2_MouseDown(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Me.MouseDown
        If e.Button = System.Windows.Forms.MouseButtons.Left Then
            drag = True
            mousex = System.Windows.Forms.Cursor.Position.X - Me.Left
            mousey = System.Windows.Forms.Cursor.Position.Y - Me.Top
        End If
    End Sub
    Private Sub Form2_MouseMove(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Me.MouseMove
        If drag Then
            Me.Top = System.Windows.Forms.Cursor.Position.Y - mousey
            Me.Left = System.Windows.Forms.Cursor.Position.X - mousex
        End If

    End Sub
    Private Sub Form2_MouseUp(ByVal sender As Object, ByVal e As System.Windows.Forms.MouseEventArgs) Handles Me.MouseUp
        drag = False

    End Sub
    Private Sub Panel1_MouseDown(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles Panel1.MouseDown
        X = Control.MousePosition.X - Me.Location.X
        Y = Control.MousePosition.Y - Me.Location.Y
    End Sub

    Private Sub Panel1_MouseMove(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles Panel1.MouseMove
        If e.Button = System.Windows.Forms.MouseButtons.Left Then
            NewPoint = Control.MousePosition
            NewPoint.X -= (X)
            NewPoint.Y -= (Y)
            Me.Location = NewPoint
        End If
    End Sub

    Private Sub PictureBox1_Click(sender As Object, e As EventArgs) Handles PictureBox1.Click
        Me.Close()
    End Sub


    Private Sub PictureBox3_Click(sender As Object, e As EventArgs) Handles PictureBox3.Click
        Me.WindowState = FormWindowState.Minimized
    End Sub
    Private Sub FlatButton7_Click(sender As Object, e As EventArgs)
        Me.Close()
    End Sub

    Private Sub FlatButton2_Click(sender As Object, e As EventArgs) Handles FlatButton2.Click
        If FlatComboBox1.Text = "Is a generic term" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("Mind-Blowing Reasons Why " + Keyword + " Is Using This Technique For Exposure.")
            anslist.Add("Gigantic Influences Of " + Keyword + ".")
            anslist.Add("Brilliant Ways To Advertise " + Keyword + ".")
            anslist.Add("Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist.Add("Think You're An Expert In " + Keyword + "? Take This Quiz Now To Find Out.")
            anslist.Add("Ugly Truth About " + Keyword + ".")
            anslist.Add("Great " + Keyword + " Ideas That You Can Share With Your Friends.")
            anslist.Add("Questions To Ask At " + Keyword + ".")
            anslist.Add("Reasons Why You Should Invest In " + Keyword + ".")
            anslist.Add("Ingenious Ways You Can Do With " + Keyword + ".")
            anslist.Add("Taboos About " + Keyword + " You Should Never Share On Twitter.")
            anslist.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist.Add("Learn How To Make More Money With " + Keyword + ".")
            anslist.Add("The Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist.Add("Innovative Approaches To Improve Your " + Keyword + ".")
            anslist.Add("Things You Probably Didn't Know About " + Keyword + ".")
            anslist.Add("Disadvantages Of " + Keyword + " And How You Can Workaround It.")
            anslist.Add("Secrets That Experts Of " + Keyword + " Don't Want You To Know.")
            anslist.Add("Small But Important Things To Observe In " + Keyword + ".")
            anslist.Add("Explanation On Why " + Keyword + " Is Important.")
            anslist.Add("Questions About " + Keyword + " You Should Answer Truthfully.")
            anslist.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist.Add("Is " + Keyword + " Still Relevant?")
            anslist.Add("The Modern Rules Of " + Keyword + ".")
            anslist2.Add("Facts About " + Keyword + " That Will Make You Think Twice.")
            anslist2.Add("How Will " + Keyword + " Be In The Future.")
            anslist2.Add("Things Your Boss Needs To Know About " + Keyword + ".")
            anslist2.Add("Things Nobody Told You About " + Keyword + ".")
            anslist2.Add("Ways To Tell You're Suffering From An Obession With " + Keyword + ".")
            anslist2.Add("Things That You Never Expect On " + Keyword + ".")
            anslist2.Add("How " + Keyword + " Can Ease Your Pain.")
            anslist2.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("Important Facts That You Should Know About " + Keyword + ".")
            anslist2.Add("Outrageous Ideas For Your " + Keyword + ".")
            anslist2.Add("The Millionaire Guide On " + Keyword + " To Help You Get Rich.")
            anslist2.Add("The Shocking Revelation of " + Keyword + ".")
            anslist2.Add("Reasons Why You Shouldn't Rely On " + Keyword + " Anymore.")
            anslist2.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist2.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist2.Add("Facts That Nobody Told You About " + Keyword + ".")
            anslist2.Add("Places That You Can Find " + Keyword + ".")
            anslist2.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist2.Add("Awesome Things You Can Learn From " + Keyword + ".")
            anslist2.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist2.Add("Why You Should Not Go To " + Keyword + ".")
            anslist2.Add("The Death Of " + Keyword + ".")
            anslist2.Add("Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist2.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist2.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist3.Add("Signs You're In Love With " + Keyword + ".")
            anslist3.Add("Difficult Things About " + Keyword + ".")
            anslist3.Add("Common Mistakes Everyone Makes In " + Keyword + ".")
            anslist3.Add("The Steps Needed For Putting " + Keyword + " Into Action.")
            anslist3.Add("Learn All About " + Keyword + " From This Politician.")
            anslist3.Add("Precious Tips To Help You Get Better At " + Keyword + ".")
            anslist3.Add("Things You Need To Know About " + Keyword + " Today.")
            anslist3.Add("These Local Practices In " + Keyword + " Are So Bizarre That They Will Make Your Jaw Drop!")
            anslist3.Add("Why Is " + Keyword + " So Famous?")
            anslist3.Add("Things You Should Do In " + Keyword + ".")
            anslist3.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist3.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist3.Add("" + Keyword + " That Had Gone Way Too Far.")
            anslist3.Add("Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist3.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist4.Add("Doubts You Should Clarify About " + Keyword + ".")
            anslist4.Add("Understand " + Keyword + " Before You Regret.")
            anslist4.Add("Things That Happen When You Are In " + Keyword + ".")
            anslist4.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist4.Add("Never Mess With " + Keyword + " And Here's The Reasons Why.")
            anslist4.Add("The Hidden Agenda Of " + Keyword + ".")
            anslist4.Add("How To Learn About " + Keyword + " In Only 10 Days.")
            anslist4.Add("The Reasons Tourists Love " + Keyword + ".")
            anslist4.Add("Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist4.Add("Learn From These Mistakes Before You Learn " + Keyword + ".")
            anslist4.Add("Reasons Why You Cannot Learn " + Keyword + " Well.")
            anslist4.Add("Why Is " + Keyword + " Considered Underrated?")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(25)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(25)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(15)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd3.Next(12)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is a brand/product" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("10 Advantages Of " + Keyword + " And How You Can Make Full Use Of It.")
            anslist.Add("10 Common Mistakes Everyone Makes In " + Keyword + ".")
            anslist.Add("Why " + Keyword + " Had Been So Popular Till Now?")
            anslist.Add("How " + Keyword + " Can Increase Your Profit!")
            anslist.Add("Is " + Keyword + " Still Relevant?")
            anslist.Add("What It's Like Dating " + Keyword + ".")
            anslist.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist.Add("10 Top Risks Of Owning " + Keyword + ".")
            anslist.Add("Simple Guidance For You In " + Keyword + ".")
            anslist.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist.Add("Here's What Industry Insiders Say About " + Keyword + ".")
            anslist.Add("﻿7 Reasons Why " + Keyword + " Is Common In USA.")
            anslist.Add("The Reasons Why We Love " + Keyword + ".")
            anslist.Add("The Reason Why Everyone Love " + Keyword + ".")
            anslist.Add("The Rank Of " + Keyword + " In Consumer's Market.")
            anslist.Add("How " + Keyword + " Can Help You Improve Your Health.")
            anslist.Add("How To Get People To Like " + Keyword + ".")
            anslist.Add("Seven Things Nobody Told You About " + Keyword + ".")
            anslist.Add("Top 5 Common Prejudices About " + Keyword + ".")
            anslist.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist.Add("The Shocking Revelation of " + Keyword + ".")
            anslist.Add("5 Quick Tips For " + Keyword + ".")
            anslist.Add("Seven Clarifications On " + Keyword + ".")
            anslist.Add("How Will " + Keyword + " Be In The Future.")
            anslist.Add("Learn How To Make More Money With " + Keyword + ".")
            anslist.Add("Seven Questions About " + Keyword + " You Should Answer Truthfully.")
            anslist.Add("Seven Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist.Add("The Ten Reasons Tourists Love " + Keyword + ".")
            anslist.Add("10 Quick Tips Regarding " + Keyword + ".")
            anslist.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist.Add("Ten Explanation On Why " + Keyword + " Is Important.")
            anslist.Add("How To Learn About " + Keyword + " In Only 10 Days.")
            anslist.Add("Learn All About " + Keyword + " From This Politician.")
            anslist.Add("7 Hidden " + Keyword + " Features That Will Make Your Life Easier.")
            anslist.Add("Is " + Keyword + " The Most Trending Thing Now?")
            anslist.Add("Why Is " + Keyword + " So Famous?")
            anslist.Add("How " + Keyword + " Can Ease Your Pain.")
            anslist.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist.Add("Ten Unexpected Ways " + Keyword + " Can Make Your Life Better.")
            anslist.Add("5 Reasons Why You Should Invest In " + Keyword + ".")
            anslist.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist.Add("5 Things That You Never Expect On " + Keyword + ".")
            anslist.Add("Seven Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist.Add("This Is Why " + Keyword + " Is So Famous!")
            anslist.Add("The Hidden Agenda Of " + Keyword + ".")
            anslist.Add("Ten Things You Didn't Know About " + Keyword + ".")
            anslist.Add("How To Have A Fantastic " + Keyword + " With Minimal Spending.")
            anslist.Add("Never Mess With " + Keyword + " And Here's The Reasons Why.")
            anslist.Add("How " + Keyword + " Makes Me Feel Good.")
            anslist2.Add("5 Ugly Truth About " + Keyword + ".")
            anslist2.Add("5 Reasons Why You Shouldn't Rely On " + Keyword + " Anymore.")
            anslist2.Add("5 Reasons Why People Love " + Keyword + ".")
            anslist2.Add("The Ten Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist2.Add("7 Secrets That Experts Of " + Keyword + " Don't Want You To Know.")
            anslist2.Add("7 Things You Should Know About " + Keyword + ".")
            anslist2.Add("Ten Disadvantages Of " + Keyword + " And How You Can Workaround It.")
            anslist2.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist2.Add("The Trending Stuff About " + Keyword + ".")
            anslist2.Add("This Is Why This Year Will Be The Year Of " + Keyword + ".")
            anslist2.Add("15 Mind-Blowing Reasons Why " + Keyword + " Is Using This Technique For Exposure")
            anslist2.Add("How To Own " + Keyword + " For Free.")
            anslist2.Add("7 Reasons The Quality Of " + Keyword + " Is So Much More Important Than Quantity.")
            anslist2.Add("Everything You Need To Know About " + Keyword + ".")
            anslist2.Add("10 Shocking Facts About " + Keyword + ".")
            anslist2.Add("5 Useful Tips From Experts In " + Keyword + ".")
            anslist2.Add("Ten Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist2.Add("Ten Important Facts That You Should Know About " + Keyword + ".")
            anslist2.Add("The Millionaire Guide On " + Keyword + " To Help You Get Rich.")
            anslist2.Add("10 Important Life Lessons " + Keyword + " Taught Us.")
            anslist2.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist2.Add("15 Reasons Why People Like " + Keyword + ".")
            anslist2.Add("Seven Top Risks Of " + Keyword + ".")
            anslist2.Add("This Year Will Be The Year of " + Keyword + ".")
            anslist2.Add("The Modern Rules Of " + Keyword + ".")
            anslist2.Add("Ten Tricks You Must Know When Using " + Keyword + ".")
            anslist2.Add("Ten New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist2.Add("How " + Keyword + " Is Going To Change Your Business Strategies.")
            anslist2.Add("" + Keyword + " Is So Famous, But Why?")
            anslist2.Add("The Billionaire Guide On " + Keyword + " That Helps You Get Rich.")
            anslist2.Add("15 Common Myths About " + Keyword + ".")
            anslist2.Add("15 Reliable Sources To Learn About " + Keyword + ".")
            anslist2.Add("Seven Signs You're In Love With " + Keyword + ".")
            anslist2.Add("How Do You Choose The Best " + Keyword + "?")
            anslist2.Add("Why Is " + Keyword + " The Most Trending Thing Now?")
            anslist2.Add("10 Tips To Avoid Failure In " + Keyword + ".")
            anslist2.Add("Seven Secrets About " + Keyword + " That Nobody Will Tell You.")
            anslist2.Add("Seven Ingenious Ways You Can Do With " + Keyword + ".")
            anslist2.Add("The Five Secrets That You Shouldn't Know About " + Keyword + ".")
            anslist2.Add("Is " + Keyword + " Any Good? Five Ways You Can Be Certain.")
            anslist2.Add("The Latest Development About " + Keyword + " That You Have To Know.")
            anslist2.Add("Seven Unbelievable Facts About " + Keyword + ".")
            anslist2.Add("Seven Reasons You Should Fall In Love With " + Keyword + ".")
            anslist2.Add("Seven Facts About " + Keyword + " That Will Make You Think Twice.")
            anslist2.Add("10 Places That You Can Find " + Keyword + ".")
            anslist2.Add("Five Things You Need To Know About " + Keyword + " Today.")
            anslist2.Add("You Will Never Thought That Owning A " + Keyword + " Could Be So Beneficial!")
            anslist2.Add("The Ultimate Revelation Of " + Keyword + ".")
            anslist2.Add("You Will Never Believe These Bizarre Truth Of " + Keyword + ".")
            anslist2.Add("" + Keyword + " Has The Answer To Everything.")
            anslist3.Add("Ten Brilliant Ways To Advertise " + Keyword + ".")
            anslist3.Add("How You Can Own " + Keyword + " With Lower Cost.")
            anslist3.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist3.Add("What's So Trendy About " + Keyword + " That Everyone Went Crazy Over It?")
            anslist3.Add("15 Advices That You Must Listen Before Studying " + Keyword + ".")
            anslist3.Add("Skills That You Can Learn From " + Keyword + ".")
            anslist3.Add("15 Latest Developments In " + Keyword + ".")
            anslist3.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist3.Add("10 Taboos About " + Keyword + " You Should Never Share On Twitter.")
            anslist3.Add("7 Awesome Things You Can Learn From Studying " + Keyword + ".")
            anslist3.Add("Fully Utilize " + Keyword + " To Enhance Your Business.")
            anslist3.Add("Why You Must Experience " + Keyword + " At Least Once In Your Lifetime.")
            anslist3.Add("7 Reasons Owning " + Keyword + " Will Change Your Life.")
            anslist3.Add("Ten Awesome Things You Can Learn From " + Keyword + ".")
            anslist3.Add("The Latest " + Keyword + " Has Finally Been Revealed!")
            anslist3.Add("5 Ways To Tell You're Suffering From An Obession With " + Keyword + ".")
            anslist3.Add("15 " + Keyword + " That Will Actually Make Your Life Better.")
            anslist3.Add("The Problem With The New " + Keyword + ".")
            anslist3.Add("10 Things About " + Keyword + " You Have To Experience It Yourself.")
            anslist3.Add("5 Top Reasons Why You Face Obstacles In Learning " + Keyword + ".")
            anslist3.Add("Understand The Background Of " + Keyword + " Now.")
            anslist3.Add("The 15 Common Stereotypes When It Comes To " + Keyword + ".")
            anslist3.Add("15 Facts About " + Keyword + " That Will Blow Your Mind.")
            anslist3.Add("10 Ways To Introduce " + Keyword + ".")
            anslist3.Add("Seven Stereotypes About " + Keyword + " That Aren't Always True.")
            anslist3.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist3.Add("5 " + Keyword + " That Had Gone Way Too Far.")
            anslist3.Add("The History of " + Keyword + ".")
            anslist3.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist3.Add("15 Things You Probably Didn't Know About " + Keyword + ".")
            anslist3.Add("5 Easy Ways To Facilitate " + Keyword + ".")
            anslist3.Add("The Top 5 Pros And Cons Of " + Keyword + ".")
            anslist3.Add("Why Is " + Keyword + " Considered Underrated?")
            anslist3.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist3.Add("Seven Shitty Things " + Keyword + " Have Done In 2015.")
            anslist3.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist3.Add("The Story Of " + Keyword + " Has Just Gone Viral!")
            anslist3.Add("This Is How " + Keyword + " Will Look Like In 10 Years Time.")
            anslist3.Add("Ten Things Your Competitors Know About " + Keyword + ".")
            anslist3.Add("Five Things Your Boss Needs To Know About " + Keyword + ".")
            anslist3.Add("10 Benefits Of " + Keyword + " That May Change Your Perspective.")
            anslist3.Add("15 Facts That Nobody Told You About " + Keyword + ".")
            anslist3.Add("15 Great Lessons You Can Learn From " + Keyword + ".")
            anslist3.Add("Ten Ways " + Keyword + " Can Improve Your Business.")
            anslist3.Add("10 Mind Numbing Facts About " + Keyword + ".")
            anslist3.Add("Master The Skills Of " + Keyword + " And Be Successful.")
            anslist3.Add("Ten Doubts About " + Keyword + " You Should Clarify.")
            anslist3.Add("" + Keyword + " Will Be A Thing Of The Past And Here's Why.")
            anslist3.Add("5 Things To Know About " + Keyword + ".")
            anslist3.Add("The 5 Secrets You Will Never Know About " + Keyword + ".")
            anslist3.Add("Think You're An Expert In " + Keyword + "? Take This Quiz Now To Find Out.")
            anslist3.Add("I Finally Tried " + Keyword + " For A Week And This Is What Happened.")
            anslist3.Add("10 Common Misconceptions About " + Keyword + ".")
            anslist3.Add("5 Innovative Approaches To Improve Your " + Keyword + ".")
            anslist3.Add("Why Are Children Getting Addicted To " + Keyword + " Nowadays?")
            anslist3.Add("5 Gigantic Influences Of " + Keyword + ".")
            anslist3.Add("5 Preparations You Should Make Before Using " + Keyword + ".")
            anslist3.Add("Ten Lessons I've Learned From " + Keyword + ".")
            anslist3.Add("10 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist3.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist3.Add("Five Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist3.Add("5 Outrageous Ideas For Your " + Keyword + ".")
            anslist3.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist3.Add("The Miracle Of " + Keyword + ".")
            anslist3.Add("The Death Of " + Keyword + ".")
            anslist3.Add("10 Features Of " + Keyword + " That Make Everyone Love It.")
            anslist3.Add("All You Need To Know About " + Keyword + ".")
            anslist3.Add("Ten Factors That Affect " + Keyword + "'s Longevity.")
            anslist3.Add("How " + Keyword + " Became A Globally Well-Known Brand.")
            anslist3.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist3.Add("20 Wonderful " + Keyword + ". Number 16 is Absolutely Stunning.")
            anslist3.Add("The Biggest Contribution Of " + Keyword + " To Humanity.")
            anslist3.Add("7 Doubts You Should Clarify About " + Keyword + ".")
            anslist3.Add("You Should Experience " + Keyword + " At Least Once In Your Lifetime And Here's Why.")
            anslist3.Add("Understanding The Background Of " + Keyword + ".")
            anslist3.Add("7 Conventional Advertising Methods That Will Jeopardize " + Keyword + ".")
            anslist3.Add("Seven Facts You Never Knew About " + Keyword + ".")
            anslist3.Add("7 Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist3.Add("" + Keyword + " Will Make You Tons Of Cash. Here's How!")
            anslist3.Add("Why Are Children So Obsessed With " + Keyword + ".")
            anslist4.Add("Think You're An Expert In " + Keyword + "? Take This Quiz Now To Find Out.")
            anslist4.Add("I Finally Tried " + Keyword + " For A Week And This Is What Happened.")
            anslist4.Add("10 Common Misconceptions About " + Keyword + ".")
            anslist4.Add("5 Innovative Approaches To Improve Your " + Keyword + ".")
            anslist4.Add("Why Are Children Getting Addicted To " + Keyword + " Nowadays?")
            anslist4.Add("5 Gigantic Influences Of " + Keyword + ".")
            anslist4.Add("5 Preparations You Should Make Before Using " + Keyword + ".")
            anslist4.Add("Ten Lessons I've Learned From " + Keyword + ".")
            anslist4.Add("10 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist4.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist4.Add("Five Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist4.Add("5 Outrageous Ideas For Your " + Keyword + ".")
            anslist4.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist4.Add("The Miracle Of " + Keyword + ".")
            anslist4.Add("The Death Of " + Keyword + ".")
            anslist4.Add("10 Features Of " + Keyword + " That Make Everyone Love It.")
            anslist4.Add("All You Need To Know About " + Keyword + ".")
            anslist4.Add("Ten Factors That Affect " + Keyword + "'s Longevity.")
            anslist4.Add("How " + Keyword + " Became A Globally Well-Known Brand.")
            anslist4.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist4.Add("20 Wonderful " + Keyword + ". Number 16 is Absolutely Stunning.")
            anslist4.Add("The Biggest Contribution Of " + Keyword + " To Humanity.")
            anslist4.Add("7 Doubts You Should Clarify About " + Keyword + ".")
            anslist4.Add("You Should Experience " + Keyword + " At Least Once In Your Lifetime And Here's Why.")
            anslist4.Add("Understanding The Background Of " + Keyword + ".")
            anslist4.Add("7 Conventional Advertising Methods That Will Jeopardize " + Keyword + ".")
            anslist4.Add("Seven Facts You Never Knew About " + Keyword + ".")
            anslist4.Add("7 Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist4.Add("" + Keyword + " Will Make You Tons Of Cash. Here's How!")
            anslist4.Add("Why Are Children So Obsessed With " + Keyword + ".")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(50)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(30)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is an event" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("What's So Trendy About " + Keyword + " That Everyone Went Crazy Over It?")
            anslist.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist.Add("Seven Things You Need To Know About " + Keyword + " Today.")
            anslist.Add("Five Great " + Keyword + " Ideas That You Can Share With Your Friends.")
            anslist.Add("One Checklist That You Should Keep In Mind Before Attending " + Keyword + ".")
            anslist.Add("You Should Experience " + Keyword + " At Least Once In Your Lifetime And Here's Why.")
            anslist.Add("15 Taboos About " + Keyword + " You Should Never Share On Twitter.")
            anslist.Add("Simple Guidance For You In " + Keyword + ".")
            anslist.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist.Add("The Ultimate Revelation Of " + Keyword + ".")
            anslist.Add("The Biggest Contribution Of " + Keyword + " To Humanity.")
            anslist.Add("Five Awesome Things You Can Learn From " + Keyword + ".")
            anslist.Add("The Miracle Of " + Keyword + ".")
            anslist.Add("" + Keyword + " Is So Famous, But Why?")
            anslist.Add("7 Important Facts That You Should Know About " + Keyword + ".")
            anslist.Add("10 Reasons Why " + Keyword + " Is Common In USA.")
            anslist.Add("7 Common Misconceptions About " + Keyword + ".")
            anslist.Add("Five Things That Happen When You Are In " + Keyword + ".")
            anslist.Add("7 Reliable Sources To Learn About " + Keyword + ".")
            anslist.Add("7 Small But Important Things To Observe In " + Keyword + ".")
            anslist.Add("The Seven Secrets That You Shouldn't Know About " + Keyword + ".")
            anslist.Add("Ten Reasons Why People Like " + Keyword + ".")
            anslist.Add("Seven Latest Tips You Can Learn When Attending " + Keyword + ".")
            anslist.Add("Seven Disadvantages Of " + Keyword + " And How You Can Workaround It.")
            anslist.Add("10 Things About " + Keyword + " You Have To Experience It Yourself.")
            anslist.Add("You Will Never Believe These Bizarre Truths Behind " + Keyword + ".")
            anslist.Add("15 Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist.Add("10 Reasons Why People Love " + Keyword + ".")
            anslist.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist.Add("7 Moments To Remember From " + Keyword + ".")
            anslist.Add("Five Advice That You Must Listen Before Embarking On " + Keyword + ".")
            anslist.Add("How To Have A Fantastic " + Keyword + " With Minimal Spending.")
            anslist.Add("7 Questions To Ask At " + Keyword + ".")
            anslist.Add("Seven Things You Should Do In " + Keyword + ".")
            anslist.Add("All You Need To Know About " + Keyword + ".")
            anslist.Add("Seven Top Risks Of Attending " + Keyword + ".")
            anslist.Add("The 7 Common Stereotypes When It Comes To " + Keyword + ".")
            anslist.Add("﻿The Cheapest Way To Earn Your Free Ticket To " + Keyword + ".")
            anslist.Add("Ten Stereotypes About " + Keyword + " That Aren't Always True.")
            anslist.Add("7 Ideas To Organize Your Own " + Keyword + ".")
            anslist.Add("10 Things You Should Know About " + Keyword + ".")
            anslist.Add("Seven Things You Didn't Know About " + Keyword + ".")
            anslist.Add("This Is Why " + Keyword + " Is So Famous!")
            anslist.Add("15 Brilliant Ways To Advertise " + Keyword + ".")
            anslist.Add("15 Things To Avoid In " + Keyword + ".")
            anslist.Add("15 Benefits Of " + Keyword + " That May Change Your Perspective.")
            anslist.Add("Why You Must Experience " + Keyword + " At Least Once In Your Lifetime.")
            anslist.Add("10 Simple (But Important) Things To Remember About " + Keyword + ".")
            anslist2.Add("10 Doubts About " + Keyword + " You Should Clarify.")
            anslist2.Add("Five Ways On How To Prepare For " + Keyword + ".")
            anslist2.Add("Do You Know How Many People Show Up At " + Keyword + ".")
            anslist2.Add("The Seven Secrets You Will Never Know About " + Keyword + ".")
            anslist2.Add("Seven " + Keyword + " Tips You Need To Learn Now.")
            anslist2.Add("10 Top Risks Of " + Keyword + ".")
            anslist2.Add("Seven Things To Expect When Attending " + Keyword + ".")
            anslist2.Add("The Hidden Agenda Of " + Keyword + ".")
            anslist2.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist2.Add("Is " + Keyword + " Any Good? Ten Ways You Can Be Certain.")
            anslist2.Add("Five Signs You're In Love With " + Keyword + ".")
            anslist2.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist2.Add("Here's Why You Should Attend " + Keyword + ".")
            anslist2.Add("The Death Of " + Keyword + ".")
            anslist2.Add("You Will Never Believe These Bizarre Truth Of " + Keyword + ".")
            anslist2.Add("10 Outrageous Ideas For Your " + Keyword + ".")
            anslist2.Add("7 Quick Tips Regarding " + Keyword + ".")
            anslist2.Add("15 Mind-Blowing Reasons Why " + Keyword + " Is Using This Technique For Exposure")
            anslist2.Add("Seven Things You Probably Didn't Know About " + Keyword + ".")
            anslist2.Add("The Reasons Why We Love " + Keyword + ".")
            anslist2.Add("How To Get People To Like " + Keyword + ".")
            anslist2.Add("Why You Should Not Go To " + Keyword + ".")
            anslist2.Add("Seven Facts That Nobody Told You About " + Keyword + ".")
            anslist2.Add("10 Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist2.Add("Five Moments That Basically Sum Up Your " + Keyword + " Experience.")
            anslist2.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist2.Add("Five Things You Won't Miss Out If You Attend " + Keyword + ".")
            anslist2.Add("7 Solid Evidences Attending " + Keyword + " Is Good For Your Career Development.")
            anslist2.Add("The Five Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist2.Add("5 Precautions You Must Take Before Attending " + Keyword + "")
            anslist2.Add("10 Exciting Parts Of Attending " + Keyword + ".")
            anslist2.Add("Seven Ugly Truth About " + Keyword + ".")
            anslist2.Add("" + Keyword + " Will Be A Thing Of The Past And Here's Why.")
            anslist2.Add("15 Common Myths About " + Keyword + ".")
            anslist2.Add("Why It Is Not The Best Time For " + Keyword + ".")
            anslist2.Add("7 Things You Should Know Before Embarking On " + Keyword + ".")
            anslist2.Add("Ten Things To Know About " + Keyword + ".")
            anslist2.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("5 Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist2.Add("7 Features Of " + Keyword + " That Make Everyone Love It.")
            anslist2.Add("7 " + Keyword + " Rituals You Should Know In 2016.")
            anslist2.Add("The Seven Steps Needed For Putting " + Keyword + " Into Action.")
            anslist2.Add("Five Easy Rules Of " + Keyword + ".")
            anslist2.Add("10 Mind Numbing Facts About " + Keyword + ".")
            anslist2.Add("7 Important Life Lessons " + Keyword + " Taught Us.")
            anslist2.Add("Learn All About " + Keyword + " From This Politician.")
            anslist2.Add("15 Reasons You Should Fall In Love With " + Keyword + ".")
            anslist2.Add("The History of " + Keyword + ".")
            anslist2.Add("Understand The Background Of " + Keyword + " Now.")
            anslist2.Add("Why Is " + Keyword + " So Famous?")
            anslist3.Add("15 Quick Tips For " + Keyword + ".")
            anslist3.Add("Is " + Keyword + " The Most Trending Thing Now?")
            anslist3.Add("Ten Reasons Why You Shouldn't Go To " + Keyword + " On Your Own.")
            anslist3.Add("Ten Ingenious Ways You Can Do With " + Keyword + ".")
            anslist3.Add("10 Ways On How To Get The Most From This " + Keyword + ".")
            anslist3.Add("What Makes " + Keyword + " So Addictive That You Never Want To Miss One?")
            anslist3.Add("Ten Fantastic Vacation Ideas For " + Keyword + ".")
            anslist3.Add("7 Various Ways To Do " + Keyword + ".")
            anslist3.Add("The Shocking Revelation of " + Keyword + ".")
            anslist3.Add("7 Facts You Never Knew About " + Keyword + ".")
            anslist3.Add("Top 10 Trends In " + Keyword + " To Watch.")
            anslist3.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist3.Add("The Modern Rules Of " + Keyword + ".")
            anslist3.Add("How " + Keyword + " Can Increase Your Profit!")
            anslist3.Add("The Reason Why Everyone Love " + Keyword + ".")
            anslist3.Add("Seven Advantages Of " + Keyword + " And How You Can Make Full Use Of It.")
            anslist3.Add("What You Should Wear To " + Keyword + ".")
            anslist3.Add("10 Great Lessons You Can Learn From " + Keyword + ".")
            anslist3.Add("5 Things That You Never Expect On " + Keyword + ".")
            anslist3.Add("Ten Things Nobody Told You About " + Keyword + ".")
            anslist3.Add("15 " + Keyword + " That Had Gone Way Too Far.")
            anslist3.Add("The Latest Trend In " + Keyword + ".")
            anslist3.Add("The Worst Advices We've Heard For " + Keyword + ".")
            anslist3.Add("Is " + Keyword + " Still Relevant?")
            anslist3.Add("5 Doubts You Should Clarify About " + Keyword + ".")
            anslist3.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist3.Add("10 Ways " + Keyword + " Can Improve Your Business.")
            anslist3.Add("The 7 Reasons Tourists Love " + Keyword + ".")
            anslist3.Add("Attending " + Keyword + " Can Be A Disaster If You Forget These 15 Rules.")
            anslist3.Add("Seven Lessons I've Learned From " + Keyword + ".")
            anslist3.Add("Seven Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist3.Add("How To Leave " + Keyword + " Without Being Noticed.")
            anslist3.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist3.Add("The Real Reason Behind " + Keyword + ".")
            anslist3.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist3.Add("7 Facts About " + Keyword + " That Will Blow Your Mind.")
            anslist3.Add("Why Is " + Keyword + " Considered Underrated?")
            anslist3.Add("Here's What Industry Insiders Say About " + Keyword + ".")
            anslist3.Add("5 Gigantic Influences Of " + Keyword + ".")
            anslist3.Add("5 Shocking Facts About " + Keyword + ".")
            anslist3.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist3.Add("How I Successfuly Organized My Very Own " + Keyword + ".")
            anslist3.Add("Seven Clarifications On " + Keyword + ".")
            anslist3.Add("Everything You Need To Know About " + Keyword + ".")
            anslist3.Add("15 Common Mistakes Everyone Makes In " + Keyword + ".")
            anslist3.Add("Five Unbelievable Facts About " + Keyword + ".")
            anslist3.Add("Five New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist3.Add("How " + Keyword + " Is Going To Change Your Business Strategies.")
            anslist3.Add("This Is How " + Keyword + " Will Look Like In 10 Years Time.")
            anslist3.Add("How Will " + Keyword + " Be In The Future.")
            anslist4.Add("Five Easy Ways To Facilitate " + Keyword + ".")
            anslist4.Add("Top Seven Fantastic Experience Of This Year's " + Keyword + ".")
            anslist4.Add("Five Things Your Boss Needs To Know About " + Keyword + ".")
            anslist4.Add("How You Can Attend " + Keyword + " With Minimal Budget.")
            anslist4.Add("Understanding The Background Of " + Keyword + ".")
            anslist4.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist4.Add("Why " + Keyword + " Had Been So Popular Till Now?")
            anslist4.Add("10 Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist4.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist4.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist4.Add("7 Thoughts You Have As " + Keyword + " Approaches.")
            anslist4.Add("The Story Of " + Keyword + " Has Just Gone Viral!")
            anslist4.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist4.Add("5 Unexpected Ways " + Keyword + " Can Make Your Life Better.")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(50)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(14)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is an industry" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist.Add("15 Ugly Truth About " + Keyword + ".")
            anslist.Add("The Hidden Agenda Of " + Keyword + ".")
            anslist.Add("Think You're An Expert In " + Keyword + "? Take This Quiz Now To Find Out.")
            anslist.Add("Ten Quick Tips Regarding " + Keyword + ".")
            anslist.Add("5 Great Tips To Earn More In The " + Keyword + " Industry.")
            anslist.Add("The Worst Advices We've Heard For " + Keyword + ".")
            anslist.Add("Why Experts Say The " + Keyword + " Industry Had Gone Way Too Far.")
            anslist.Add("7 Facts That Nobody Told You About " + Keyword + ".")
            anslist.Add("" + Keyword + " Has The Answer To Everything.")
            anslist.Add("The 5 Secrets That You Shouldn't Know About " + Keyword + ".")
            anslist.Add("The Millionaire Guide On " + Keyword + " To Help You Get Rich.")
            anslist.Add("Understand The Background Of " + Keyword + " Now.")
            anslist.Add("15 Reasons Why You Should Invest In " + Keyword + ".")
            anslist.Add("7 Things You Should Know Before Getting Into The " + Keyword + " Industry.")
            anslist.Add("5 Precious Tips To Help You Get Better In " + Keyword + " Industry.")
            anslist.Add("Ten Gigantic Influences Of " + Keyword + ".")
            anslist.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist.Add("There's No Point Doing " + Keyword + " If You're Not Doing It Right.")
            anslist.Add("Ten Advices That You Must Listen Before Studying " + Keyword + ".")
            anslist.Add("10 Things That You Never Expect On " + Keyword + ".")
            anslist.Add("Here's What Industry Insiders Say About " + Keyword + ".")
            anslist.Add("Everyone Is Flocking To Work In The " + Keyword + " Industry. But Why?")
            anslist.Add("Seven Precious Tips To Help You Get Better At " + Keyword + ".")
            anslist.Add("7 Stereotypes About " + Keyword + " That Aren't Always True.")
            anslist.Add("Seven Things To Know About " + Keyword + ".")
            anslist.Add("Ten Mind Numbing Facts About " + Keyword + ".")
            anslist.Add("Learn All About " + Keyword + " From This Politician.")
            anslist.Add("Is " + Keyword + " The Most Trending Thing Now?")
            anslist.Add("15 Doubts About " + Keyword + " You Should Clarify.")
            anslist.Add("5 Small But Important Things To Observe In " + Keyword + ".")
            anslist.Add("These Local Practices In " + Keyword + " Are So Bizarre That They Will Make Your Jaw Drop!")
            anslist.Add("7 Common Misconceptions About " + Keyword + ".")
            anslist.Add("7 Fishy Things That Nobody Told You About " + Keyword + " Industry.")
            anslist.Add("Everything You Need To Know About " + Keyword + ".")
            anslist.Add("What Causes The Emerging Trend Of " + Keyword + " Industry In Asia?")
            anslist.Add("5 Clarifications On " + Keyword + ".")
            anslist.Add("All You Need To Know About " + Keyword + ".")
            anslist.Add("Ten Crazy Trends In The " + Keyword + " Industry.")
            anslist.Add("Five Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist.Add("Ten Doubts You Should Clarify About " + Keyword + ".")
            anslist.Add("This Is Why This Year Will Be The Year Of " + Keyword + ".")
            anslist.Add("Ten Outrageous Ideas For Your " + Keyword + ".")
            anslist.Add("Seven Unbelievable Facts About " + Keyword + ".")
            anslist.Add("Seven Things You Didn't Know About " + Keyword + ".")
            anslist.Add("The Ten Common Stereotypes When It Comes To " + Keyword + ".")
            anslist.Add("Seven Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist.Add("Top 15 " + Keyword + " Related Trends To Keep In View.")
            anslist.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist.Add("Five Things Your Competitors Know About " + Keyword + ".")
            anslist2.Add("Understanding The Background Of " + Keyword + ".")
            anslist2.Add("15 Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist2.Add("The Hidden Agenda Of " + Keyword + " Industry.")
            anslist2.Add("Five Reliable Sources To Learn About " + Keyword + ".")
            anslist2.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist2.Add("5 Things About " + Keyword + " You Have To Experience It Yourself.")
            anslist2.Add("Top Seven Common Prejudices About " + Keyword + ".")
            anslist2.Add("The Ultimate Revelation Of " + Keyword + ".")
            anslist2.Add("How To Get People To Like " + Keyword + ".")
            anslist2.Add("Why You Shouldn't Venture Into The " + Keyword + " Industry Now.")
            anslist2.Add("15 Reasons Why You Are A Rookie In " + Keyword + ".")
            anslist2.Add("Five Things You Probably Didn't Know About " + Keyword + ".")
            anslist2.Add("Five Brilliant Ways To Advertise " + Keyword + ".")
            anslist2.Add("15 Useful Tips From Experts In " + Keyword + ".")
            anslist2.Add("7 Things You Need To Know About " + Keyword + " Today.")
            anslist2.Add("7 Very Common Misconceptions About The " + Keyword + " Industry.")
            anslist2.Add("Learning " + Keyword + " Is Not Difficult At All! You Just Need A Great Teacher!")
            anslist2.Add("7 Pros And Cons Of Being In " + Keyword + " Industry.")
            anslist2.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist2.Add("What " + Keyword + " Industry Really Is.")
            anslist2.Add("" + Keyword + " Is So Famous, But Why?")
            anslist2.Add("This Is How " + Keyword + " Will Look Like In 10 Years Time.")
            anslist2.Add("5 Reasons Why People Like " + Keyword + ".")
            anslist2.Add("10 Reliable Sources To Learn About The " + Keyword + " Industry.")
            anslist2.Add("10 Reasons Why You Shouldn't Rely On " + Keyword + " Anymore.")
            anslist2.Add("The Advantages Of Being In " + Keyword + " Industry.")
            anslist2.Add("The Reasons Why We Love " + Keyword + ".")
            anslist2.Add("The Miracle Of " + Keyword + ".")
            anslist2.Add("7 Ways To Achieve Your Goals In " + Keyword + " Faster.")
            anslist2.Add("Learn From These Mistakes Before You Learn " + Keyword + ".")
            anslist2.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("15 Reasons Why You Cannot Learn " + Keyword + " Well.")
            anslist2.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist2.Add("Why Is " + Keyword + " So Famous?")
            anslist2.Add("10 Things To Avoid In " + Keyword + ".")
            anslist2.Add("Are You Ready For This Year's " + Keyword + " Industry?")
            anslist2.Add("The Shocking Revelation of " + Keyword + ".")
            anslist2.Add("The Latest Trend In " + Keyword + ".")
            anslist2.Add("15 Top Hidden Risks In The " + Keyword + " Industry.")
            anslist2.Add("Ten New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist2.Add("Seven Ingenious Ways You Can Do With " + Keyword + ".")
            anslist2.Add("5 Things You Should Know About " + Keyword + ".")
            anslist2.Add("Top Seven Trends In " + Keyword + " To Watch.")
            anslist2.Add("Working In The " + Keyword + " Industry Can Be Disastrous If You Don't Follow These 10 Rules!")
            anslist2.Add("The Ten Secrets You Will Never Know About " + Keyword + ".")
            anslist2.Add("Seven Reasons Why People Love " + Keyword + ".")
            anslist2.Add("15 Latest Developments In " + Keyword + ".")
            anslist2.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist2.Add("Understand " + Keyword + " Before You Regret.")
            anslist2.Add("Seven Common Myths About The " + Keyword + " Industry.")
            anslist3.Add("The Biggest Contribution Of " + Keyword + " To Humanity.")
            anslist3.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist3.Add("Why " + Keyword + " Had Been So Popular Till Now?")
            anslist3.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist3.Add("7 Tips To Avoid Failure In " + Keyword + ".")
            anslist3.Add("7 Explanation On Why " + Keyword + " Is Important.")
            anslist3.Add("5 Taboos About " + Keyword + " You Should Never Share On Twitter.")
            anslist3.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist3.Add("7 Things Nobody Told You About " + Keyword + ".")
            anslist3.Add("Seven Important Facts That You Should Know About The " + Keyword + " Industry.")
            anslist3.Add("" + Keyword + " Will Be A Thing Of The Past And Here's Why.")
            anslist3.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist3.Add("Ten Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist3.Add("Why You Must Experience " + Keyword + " At Least Once In Your Lifetime.")
            anslist3.Add("5 Easy Rules Of " + Keyword + ".")
            anslist3.Add("Five Ways To Learn " + Keyword + " Effectively.")
            anslist3.Add("10 Difficult Things About " + Keyword + ".")
            anslist3.Add("Five Reasons Why You're Still A Rookie In " + Keyword + ".")
            anslist3.Add("Understanding The Background Of " + Keyword + " Industry.")
            anslist3.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist3.Add("The Death Of " + Keyword + ".")
            anslist3.Add("How " + Keyword + " Can Increase Your Profit!")
            anslist3.Add("10 Secrets That Experts Of " + Keyword + " Don't Want You To Know.")
            anslist3.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist3.Add("Five Moments To Remember From " + Keyword + ".")
            anslist3.Add("15 Lessons I've Learned From " + Keyword + ".")
            anslist3.Add("The History of " + Keyword + ".")
            anslist3.Add("Ten Awesome Things You Can Learn From " + Keyword + ".")
            anslist3.Add("Is " + Keyword + " Still Relevant?")
            anslist3.Add("7 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist3.Add("Be A Pioneer In The " + Keyword + " Industry. Here's What You'll Need.")
            anslist3.Add("15 Teachings That Can Empower Your Business In " + Keyword + ".")
            anslist3.Add("5 Things Your Competitors Know About The " + Keyword + " Industry.")
            anslist3.Add("Simple Guidance For You In " + Keyword + ".")
            anslist3.Add("15 Disadvantages Of " + Keyword + " And How You Can Workaround It.")
            anslist3.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist3.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist3.Add("7 Facts You Never Knew About " + Keyword + ".")
            anslist3.Add("The Reason Why Everyone Love " + Keyword + ".")
            anslist3.Add("Seven Quick Tips For " + Keyword + ".")
            anslist3.Add("15 " + Keyword + " Trends You Should Know Before Even Starting Your Business.")
            anslist3.Add("Seven Things Your Boss Needs To Know About " + Keyword + ".")
            anslist3.Add("How Will " + Keyword + " Be In The Future.")
            anslist3.Add("15 Great Lessons You Can Learn From " + Keyword + ".")
            anslist3.Add("Five Awesome Lessons You Can Learn From Studying The " + Keyword + " Industry.")
            anslist3.Add("Seven Shocking Facts About " + Keyword + ".")
            anslist3.Add("The Ultimate Revelation On The " + Keyword + " Industry.")
            anslist3.Add("The Modern Rules Of " + Keyword + ".")
            anslist3.Add("Ten Ways To Introduce " + Keyword + ".")
            anslist3.Add("Seven Common Mistakes Everyone Makes In " + Keyword + ".")
            anslist4.Add("Learn The Truth About " + Keyword + " Industry In The Next 60 Seconds.")
            anslist4.Add("How To Have A Fantastic " + Keyword + " With Minimal Spending.")
            anslist4.Add("The Story Of " + Keyword + " Has Just Gone Viral!")
            anslist4.Add("What Will The " + Keyword + " Industry Be Like In The Next 50 Years?")
            anslist4.Add("Seven Questions About " + Keyword + " You Should Answer Truthfully.")
            anslist4.Add("5 Struggles Only People In " + Keyword + " Industry Will Understand.")
            anslist4.Add("Five Reasons You Should Fall In Love With " + Keyword + ".")
            anslist4.Add("10 Top Reasons Why You Face Obstacles In Learning " + Keyword + ".")
            anslist4.Add("Five Important Facts That You Should Know About " + Keyword + ".")
            anslist4.Add("Is " + Keyword + " Any Good? 5 Ways You Can Be Certain.")
            anslist4.Add("Ten Factors That Affect " + Keyword + "'s Longevity.")
            anslist4.Add("How To Learn About " + Keyword + " In Only 10 Days.")
            anslist4.Add("The 7 Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist4.Add("Seven Awesome Things You Can Learn From Studying " + Keyword + ".")
            anslist4.Add("What's So Trendy About " + Keyword + " That Everyone Went Crazy Over It?")
            anslist4.Add("Seven Useful Tips From Experienced " + Keyword + " Veteran.")
            anslist4.Add("The Real Reason We Need To Stop Trying Too Hard In " + Keyword + ".")
            anslist4.Add("7 Things That Happen When You Are In " + Keyword + ".")
            anslist4.Add("Skills That You Can Learn From " + Keyword + ".")
            anslist4.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist4.Add("﻿Ten Great " + Keyword + " Ideas That You Can Share With Your Friends.")
            anslist4.Add("15 Facts About " + Keyword + " That Will Make You Think Twice.")
            anslist4.Add("Winning Philosophy For The " + Keyword + " Industry.")
            anslist4.Add("Skills That You Can Learn In The " + Keyword + " Industry.")
            anslist4.Add("What You Can Learn From Politician About The " + Keyword + " Industry.")
            anslist4.Add("10 Little Tricks To Achieve The Best Results In " + Keyword + ".")
            anslist4.Add("Ten Benefits Of " + Keyword + " That May Change Your Perspective.")
            anslist4.Add("Ten Top Risks Of " + Keyword + ".")
            anslist4.Add("The Reasons Why We Love The " + Keyword + " Industry.")
            anslist4.Add("7 Common Myths About " + Keyword + ".")
            anslist4.Add("Master The Skills Of " + Keyword + " And Be Successful.")
            anslist4.Add("15 Ways " + Keyword + " Can Improve Your Business.")
            anslist4.Add("5 Things Your Boss Needs To Know About The " + Keyword + " Industry.")
            anslist4.Add("Seven " + Keyword + " Tips You Need To Learn Now.")
            anslist4.Add("How To Be Successful In The " + Keyword + " Industry.")
            anslist4.Add("7 Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist4.Add("Ten Secrets About " + Keyword + " That Nobody Will Tell You.")
            anslist4.Add("You Will Never Believe These Bizarre Truth Of " + Keyword + ".")
            anslist4.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist4.Add("Seven Moments That Basically Sum Up Your " + Keyword + " Experience.")
            anslist4.Add("Five Facts About " + Keyword + " That Will Blow Your Mind.")
            anslist4.Add("This Year Will Be The Year of " + Keyword + ".")
            anslist4.Add("10 Advantages Of " + Keyword + " And How You Can Make Full Use Of It.")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(50)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(43)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is a location" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("Why Is " + Keyword + " So Famous?")
            anslist.Add("Ten Reliable Sources To Learn About " + Keyword + ".")
            anslist.Add("Seven Reasons Why You Should Go " + Keyword + " For Your Next Vacation.")
            anslist.Add("5 Hidden Travel Destinations In " + Keyword + " For Travelers On A Budget.")
            anslist.Add("5 Unbelievable Facts About " + Keyword + ".")
            anslist.Add("Seven Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist.Add("7 Features Of " + Keyword + " That Make Everyone Love It.")
            anslist.Add("10 Moments To Remember From " + Keyword + ".")
            anslist.Add("The Reason Why Everyone Love " + Keyword + ".")
            anslist.Add("Ten Things About " + Keyword + " You Have To Experience It Yourself.")
            anslist.Add("Five Signs You're In Love With " + Keyword + ".")
            anslist.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist.Add("15 Reasons Why You Should Invest In " + Keyword + ".")
            anslist.Add("5 Simple (But Important) Things To Remember About " + Keyword + ".")
            anslist.Add("The Latest Trend In " + Keyword + ".")
            anslist.Add("Five Unconventional Ways To Really Understand The Beauty of " + Keyword + ".")
            anslist.Add("Why You Should Not Go To " + Keyword + ".")
            anslist.Add("Ten Ugly Truth About " + Keyword + ".")
            anslist.Add("5 Benefits Of " + Keyword + " That May Change Your Perspective.")
            anslist.Add("Top Ten Common Prejudices About " + Keyword + ".")
            anslist.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist.Add("7 Top Risks Of Visiting " + Keyword + ".")
            anslist.Add("Ten Latest Developments In " + Keyword + ".")
            anslist.Add("Discover The Top Secret " + Keyword + " Hideaways.")
            anslist.Add("7 Things To Know About " + Keyword + ".")
            anslist.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist.Add("5 Tricks You Should Know When Travelling To " + Keyword + ".")
            anslist.Add("How " + Keyword + " Can Help You Improve Your Health.")
            anslist.Add("7 Doubts About " + Keyword + " You Should Clarify.")
            anslist.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist.Add("15 Things You Didn't Know About " + Keyword + ".")
            anslist.Add("Never Get Lost In " + Keyword + " Again.")
            anslist.Add("How I Traveled " + Keyword + " In 5 Days.")
            anslist.Add("Seven Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist.Add("20 Wonderful " + Keyword + ". Number 16 is Absolutely Stunning.")
            anslist.Add("5 Undeniable Signs You Grew Up In " + Keyword + ".")
            anslist.Add("Five New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist.Add("15 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist.Add("The Five Secrets You Will Never Know About " + Keyword + ".")
            anslist.Add("Why Are Children So Obsessed With " + Keyword + ".")
            anslist.Add("Five Places To Stay When You're In " + Keyword + ".")
            anslist.Add("Top 5 Tourism Destinations In " + Keyword + ".")
            anslist.Add("This Is Why " + Keyword + " Is So Famous!")
            anslist.Add("When At " + Keyword + ", Do As The " + Keyword + "-ans Say.")
            anslist.Add("5 Reasons You Should Fall In Love With " + Keyword + ".")
            anslist.Add("One Checklist That You Should Keep In Mind Before Visiting " + Keyword + ".")
            anslist.Add("Ten Realizations You Have When You Move To " + Keyword + ".")
            anslist.Add("The Shocking Revelation of " + Keyword + ".")
            anslist.Add("5 Things To Avoid In " + Keyword + ".")
            anslist2.Add("Why Is " + Keyword + " Considered Underrated?")
            anslist2.Add("How Will " + Keyword + " Be In The Future.")
            anslist2.Add("" + Keyword + " Is So Famous, But Why?")
            anslist2.Add("Why You Must Experience " + Keyword + " At Least Once In Your Lifetime.")
            anslist2.Add("10 Lessons I've Learned From " + Keyword + ".")
            anslist2.Add("Dining In " + Keyword + ": Here's What You Need To Know About The Food.")
            anslist2.Add("15 Things That Happen When You Are In " + Keyword + ".")
            anslist2.Add("Ten Facts You Never Knew About " + Keyword + ".")
            anslist2.Add("A Fantastic Trip At " + Keyword + " With Minimal Spending? Here's How.")
            anslist2.Add("7 Factors That Affect " + Keyword + "'s Longevity.")
            anslist2.Add("5 Stereotypes About " + Keyword + " That Aren't Always True.")
            anslist2.Add("Everything You Need To Know About " + Keyword + ".")
            anslist2.Add("This Is How " + Keyword + " Will Look Like In 10 Years Time.")
            anslist2.Add("10 Facts About " + Keyword + " That Will Blow Your Mind.")
            anslist2.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("Where Do I Start? The Beginner's Travel Guide To Explore " + Keyword + " In Seven Days.")
            anslist2.Add("Ten Ways " + Keyword + " Can Improve Your Business.")
            anslist2.Add("The 5 Common Stereotypes When It Comes To " + Keyword + ".")
            anslist2.Add("The History of " + Keyword + ".")
            anslist2.Add("5 Unexpected Ways " + Keyword + " Can Make Your Life Better.")
            anslist2.Add("Prevent Culture Shock! 5 Things You Should Know About " + Keyword + " And Their People!")
            anslist2.Add("The Story Of " + Keyword + " Has Just Gone Viral!")
            anslist2.Add("7 Taboos About " + Keyword + " You Should Never Share On Twitter.")
            anslist2.Add("Five Fantastic Vacations In " + Keyword + ".")
            anslist2.Add("Ten Reasons You Should Go To " + Keyword + " Right Now.")
            anslist2.Add("Is " + Keyword + " The Most Trending Thing Now?")
            anslist2.Add("5 Useful Traveling Tips For Those Who Wish To Visit " + Keyword + ".")
            anslist2.Add("The Five Reasons Tourists Love " + Keyword + ".")
            anslist2.Add("5 Life-Changing Experiences In " + Keyword + " You Should Have Before You Die.")
            anslist2.Add("How To Get People To Like " + Keyword + ".")
            anslist2.Add("The Reasons Why We Love " + Keyword + ".")
            anslist2.Add("You Should Experience " + Keyword + " At Least Once In Your Lifetime And Here's Why.")
            anslist2.Add("Seven Doubts You Should Clarify About " + Keyword + ".")
            anslist2.Add("15 Ways To Introduce " + Keyword + ".")
            anslist2.Add("The Ten Secrets That You Shouldn't Know About " + Keyword + ".")
            anslist2.Add("Ten Small But Important Things To Observe In " + Keyword + ".")
            anslist2.Add("10 Reasons Why People Love " + Keyword + ".")
            anslist2.Add("The Ultimate Revelation Of " + Keyword + ".")
            anslist2.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist2.Add("15 Things You Should Do In " + Keyword + ".")
            anslist2.Add("Simple Guidance For You In " + Keyword + ".")
            anslist2.Add("Travelling To " + Keyword + "? Here's How You Can Minimize Your Savings.")
            anslist2.Add("Ten Common Myths About " + Keyword + ".")
            anslist2.Add("10 Shocking Facts About " + Keyword + ".")
            anslist2.Add("15 Things That You Never Expect On " + Keyword + ".")
            anslist2.Add("You Will Never Believe These Bizarre Truths Behind " + Keyword + ".")
            anslist2.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist2.Add("Five " + Keyword + " That Will Actually Make Your Life Better.")
            anslist2.Add("5 Things Your Boss Needs To Know About " + Keyword + ".")
            anslist2.Add("Ten Reasons Why People Like " + Keyword + ".")
            anslist3.Add("10 Things You Probably Didn't Know About " + Keyword + ".")
            anslist3.Add("15 Clarifications On " + Keyword + ".")
            anslist3.Add("You Will Never Believe These Bizarre Truth Of " + Keyword + ".")
            anslist3.Add("﻿The Cheapest Way To Earn Your Free Ticket To " + Keyword + ".")
            anslist3.Add("Romantic Getaway At " + Keyword + ".")
            anslist3.Add("Travelling In " + Keyword + " Can Be Disastrous If You Don't Follow These Five Rules.")
            anslist3.Add("How I Successfully Made It To " + Keyword + ".")
            anslist3.Add("The Trending Stuff In " + Keyword + ".")
            anslist3.Add("7 Mind Numbing Facts About " + Keyword + ".")
            anslist3.Add("Ten Things You Should Know About " + Keyword + ".")
            anslist3.Add("Seven Facts About " + Keyword + " That Will Make You Think Twice.")
            anslist3.Add("15 Amazing Places To Visit When You're In " + Keyword + ".")
            anslist3.Add("Seven Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist3.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist3.Add("5 Things You Need To Know About " + Keyword + " Today.")
            anslist3.Add("10 Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist3.Add("Why It Is Not The Best Time To Visit " + Keyword + " Now.")
            anslist3.Add("7 Beautiful Reasons We Can't Help But Fall In Love With " + Keyword + ".")
            anslist3.Add("What's So Trendy About " + Keyword + " That Everyone Went Crazy Over It?")
            anslist3.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist4.Add("All You Need To Know About " + Keyword + ".")
            anslist4.Add("Five Important Facts That You Should Know About " + Keyword + ".")
            anslist4.Add("Understanding The Background Of " + Keyword + ".")
            anslist4.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist4.Add("10 Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist4.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist4.Add("Five Awesome Things You Can Learn From " + Keyword + ".")
            anslist4.Add("15 Top Risks Of " + Keyword + ".")
            anslist4.Add("The 5 Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist4.Add("Top 15 Trends In " + Keyword + " To Watch.")
            anslist4.Add("Five Things Nobody Told You About " + Keyword + ".")
            anslist4.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist4.Add("Five Facts That Nobody Told You About " + Keyword + ".")
            anslist4.Add("Understand The Background Of " + Keyword + " Now.")
            anslist4.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist4.Add("How To Leave " + Keyword + " Without Being Noticed.")
            anslist4.Add("Five Secrets About " + Keyword + " That Nobody Will Tell You.")
            anslist4.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist4.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist4.Add("5 Brilliant Ways To Advertise " + Keyword + ".")
            anslist4.Add("These Local Practices In " + Keyword + " Are So Bizarre That They Will Make Your Jaw Drop!")
            anslist4.Add("7 Common Misconceptions About " + Keyword + ".")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(20)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(23)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is a person's name" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("How " + Keyword + " Is Going To Change Your Business Strategies.")
            anslist.Add("This Story Behind " + Keyword + " Will Haunt You Forever!")
            anslist.Add("The Ultimate Revelation Of " + Keyword + ".")
            anslist.Add("The Biggest Contribution Of " + Keyword + " To Humanity.")
            anslist.Add("Seven Reasons You Should Date " + Keyword + ".")
            anslist.Add("The 5 Secrets That You Shouldn't Know About " + Keyword + ".")
            anslist.Add("Five Quick Tips For " + Keyword + ".")
            anslist.Add("You Will Never Believe These Bizarre Truth Behind " + Keyword + ".")
            anslist.Add("5 Things Nobody Told You About " + Keyword + ".")
            anslist.Add("" + Keyword + "'s 7 Most Inspiring Quotes.")
            anslist.Add("10 Reasons Why You Should Fall in Love With " + Keyword + ".")
            anslist.Add("15 Traits You Can Copy From " + Keyword + ".")
            anslist.Add("5 Unexpected Lessons From " + Keyword + ".")
            anslist.Add("Seven Facts About " + Keyword + " That Will Blow Your Mind.")
            anslist.Add("Seven Important Life Lessons " + Keyword + " Taught Us.")
            anslist.Add("This Is What " + Keyword + " Indulge In During Cheat Days.")
            anslist.Add("Why " + Keyword + " Had Been So Popular Till Now?")
            anslist.Add("Ten Qualities You Should Know About " + Keyword + ".")
            anslist.Add("Never Mess With " + Keyword + " And Here's The Reasons Why.")
            anslist.Add("15 Beautiful Reasons We Can't Help But Fall In Love With " + Keyword + ".")
            anslist.Add("10 Facts You Never Knew About " + Keyword + ".")
            anslist.Add("The Shocking Revelation of " + Keyword + ".")
            anslist.Add("15 Mind Numbing Facts About " + Keyword + ".")
            anslist.Add("You Will Never Thought That Knowing " + Keyword + " Could Be So Beneficial!")
            anslist.Add("Seven Things To Know About " + Keyword + ".")
            anslist.Add("Five Shocking Facts About " + Keyword + ".")
            anslist.Add("This Is Why " + Keyword + " Is So Famous!")
            anslist.Add("Why Is " + Keyword + " So Famous?")
            anslist.Add("Ten Reliable Sources To Learn About " + Keyword + ".")
            anslist.Add("Seven Things I Hate About " + Keyword + ".")
            anslist.Add("Ten Reasons Why People Love " + Keyword + ".")
            anslist.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist.Add("Five Features Of " + Keyword + " That Make Everyone Love It.")
            anslist.Add("5 Shitty Things " + Keyword + " Have Done In 2015.")
            anslist.Add("Seven Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist.Add("5 Things That Happen When You're Dating " + Keyword + ".")
            anslist.Add("10 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist.Add("Seven Reasons Why People Like " + Keyword + ".")
            anslist.Add("15 Things You Need To Know About " + Keyword + " Today.")
            anslist.Add("Ten Questions About " + Keyword + " You Should Answer Truthfully.")
            anslist.Add("What You Can Learn From A Person Like " + Keyword + ".")
            anslist.Add("Seven Reasons Why You Should Adore " + Keyword + ".")
            anslist.Add("Can You Be The Next " + Keyword + "?")
            anslist.Add("Ten What Ifs That Almost Threw " + Keyword + " Off His/ Her Track.")
            anslist.Add("7 " + Keyword + " That Had Gone Way Too Far.")
            anslist.Add("Ten Secrets You Will Not Want To Know About " + Keyword + ".")
            anslist.Add("How Will " + Keyword + " Be In The Future.")
            anslist.Add("15 Things About " + Keyword + " And Why You Should Change Your Role Model!")
            anslist.Add("This Is How " + Keyword + " Will Look Like In 10 Years Time.")
            anslist2.Add("15 Doubts About " + Keyword + " You Should Clarify.")
            anslist2.Add("Quiz: How Much Do You Know about " + Keyword + "?")
            anslist2.Add("Never Mess With " + Keyword + "! Here's Why.")
            anslist2.Add("5 Reasons You Should Fall In Love With " + Keyword + ".")
            anslist2.Add("The History of " + Keyword + ".")
            anslist2.Add("7 Ugly Truth About " + Keyword + ".")
            anslist2.Add("Understanding The Background Of " + Keyword + ".")
            anslist2.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist2.Add("I Will Tell You The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("" + Keyword + " Will Make You Tons Of Cash. Here's How!")
            anslist2.Add("7 Important Facts That You Should Know About " + Keyword + ".")
            anslist2.Add("10 Facts That Nobody Told You About " + Keyword + ".")
            anslist2.Add("This Year Will Be The Year of " + Keyword + ".")
            anslist2.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist2.Add("The Hidden Agenda Of " + Keyword + ".")
            anslist2.Add("Five Awesome Things You Can Learn From " + Keyword + ".")
            anslist2.Add("﻿What It's Like Dating " + Keyword + ".")
            anslist2.Add("Master The Skills Of " + Keyword + " And Be Successful.")
            anslist2.Add("7 Common Myths About " + Keyword + ".")
            anslist2.Add("10 Places That You Can Find " + Keyword + ".")
            anslist2.Add("Understand The Background Of " + Keyword + " Now.")
            anslist2.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist2.Add("Seven Common Misconceptions About " + Keyword + ".")
            anslist2.Add("The Ten Common Stereotypes When It Comes To " + Keyword + ".")
            anslist2.Add("5 Principles That You Can Learn From " + Keyword + ".")
            anslist2.Add("Seven Stories of " + Keyword + " That Will Inspire You.")
            anslist2.Add("How " + Keyword + " Can Increase Your Profit!")
            anslist2.Add("The Reason Why Everyone Love " + Keyword + ".")
            anslist2.Add("Seven Things You Should Know About " + Keyword + ".")
            anslist2.Add("Five Gigantic Influences Of " + Keyword + ".")
            anslist2.Add("What's So Trendy About " + Keyword + " That Everyone Went Crazy Over It?")
            anslist2.Add("5 Things You Should Know Before You Date " + Keyword + ".")
            anslist2.Add("5 Doubts You Should Clarify About " + Keyword + ".")
            anslist2.Add("How To Learn About " + Keyword + " In Only 10 Days.")
            anslist2.Add("15 Unbelievable Facts About " + Keyword + ".")
            anslist2.Add("This Could Be " + Keyword + "'s Worst Nightmare...")
            anslist2.Add("The Reasons Why We Love " + Keyword + ".")
            anslist2.Add("Five Books That " + Keyword + " Thinks Everyone Should Read.")
            anslist2.Add("Why Are Children So Obsessed With " + Keyword + ".")
            anslist2.Add("The Biggest Contribution Of " + Keyword + ".")
            anslist2.Add("The 15 Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist2.Add("How To Think Like " + Keyword + "?")
            anslist2.Add("How To Get People To Like " + Keyword + ".")
            anslist2.Add("7 Ways To Be Like " + Keyword + ".")
            anslist2.Add("Five Great Lessons You Can Learn From " + Keyword + ".")
            anslist2.Add("Learn The Truth About " + Keyword + " In The Next 60 Seconds.")
            anslist2.Add("This Is Why This Year Will Be The Year Of " + Keyword + ".")
            anslist2.Add("Here's What Industry Insiders Say About " + Keyword + ".")
            anslist2.Add("Ten Gossips You Didn't Know About " + Keyword + ".")
            anslist2.Add("Ten Lessons I've Learned From " + Keyword + ".")
            anslist3.Add("Ten Ways To Tell You're Suffering From An Obession With " + Keyword + ".")
            anslist3.Add("Seven New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist3.Add("What Do " + Keyword + " And You Have In Common?")
            anslist3.Add("Seven Great Things " + Keyword + " Did In Difficult Times.")
            anslist3.Add("5 Ways " + Keyword + " Will Make You A Better Wo(Man).")
            anslist3.Add("15 Things Your Boss Needs To Know About " + Keyword + ".")
            anslist3.Add("5 Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist3.Add("How " + Keyword + " Can Help You Improve Your Health.")
            anslist3.Add("15 Ways " + Keyword + " Can Improve Your Business.")
            anslist3.Add("The Five Secrets You Will Never Know About " + Keyword + ".")
            anslist3.Add("10 Difficult Things About " + Keyword + ".")
            anslist3.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist3.Add("Everything You Need To Know About " + Keyword + ".")
            anslist3.Add("The Story Of " + Keyword + " Has Just Gone Viral!")
            anslist3.Add("15 Quick Tips Regarding " + Keyword + ".")
            anslist3.Add("Seven Things You Probably Didn't Know About " + Keyword + ".")
            anslist3.Add("You Will Never Believe These Bizarre Truth Of " + Keyword + ".")
            anslist3.Add("All You Need To Know About " + Keyword + ".")
            anslist3.Add("Skills That You Can Learn From " + Keyword + ".")
            anslist3.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist4.Add("Five Reasons Why You Can't Help But Like " + Keyword + ".")
            anslist4.Add("The Untold Story Of " + Keyword + ".")
            anslist4.Add("" + Keyword + " Is So Famous, But Why?")
            anslist4.Add("Seven Stereotypes About " + Keyword + " That Aren't Always True.")
            anslist4.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist4.Add("5 Secrets About " + Keyword + " That Nobody Will Tell You.")
            anslist4.Add("Is " + Keyword + " The Most Trending Thing Now?")
            anslist4.Add("" + Keyword + " Has The Answer To Everything.")
            anslist4.Add("Seven Mind-Blowing Reasons Why " + Keyword + " Is Using This Technique For Exposure")
            anslist4.Add("What It's Like To Live With " + Keyword + ".")
            anslist4.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist4.Add("What Will " + Keyword + " Be Like In The Next 50 Years?")
            anslist4.Add("Why You Must Experience " + Keyword + " At Least Once In Your Lifetime.")
            anslist4.Add("Seven Secrets About " + Keyword + " That Has Never Been Revealed For The Past 50 Years.")
            anslist4.Add("Is " + Keyword + " The Most Popular Figure Now?")
            anslist4.Add("The Story Of " + Keyword + " As Told In 15 Photos.")
            anslist4.Add("Seven Things You Didn't Know About " + Keyword + ".")
            anslist4.Add("Five Questions To Ask At " + Keyword + ".")
            anslist4.Add("Seven Reasons Why You Shouldn't Rely On " + Keyword + " Anymore.")
            anslist4.Add("Top Five Common Prejudices About " + Keyword + ".")
            anslist4.Add("Learn How To Make More Money With " + Keyword + ".")
            anslist4.Add("The 7 Reasons Tourists Love " + Keyword + ".")
            anslist4.Add("Five Signs You're In Love With " + Keyword + ".")
            anslist4.Add("Is " + Keyword + " Still Relevant?")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(20)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(25)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
        If FlatComboBox1.Text = "Is a skill" Then
            Dim anslist As New ArrayList
            Dim anslist2 As New ArrayList
            Dim anslist3 As New ArrayList
            Dim anslist4 As New ArrayList
            Dim Keyword As String = FlatTextBox4.Text
            Label5.Text = FlatTextBox4.Text
            anslist.Add("Seven Reliable Sources To Learn About " + Keyword + ".")
            anslist.Add("15 Disadvantages Of " + Keyword + " And How You Can Workaround It.")
            anslist.Add("The Worst Advices We've Heard For " + Keyword + ".")
            anslist.Add("The Death Of " + Keyword + ".")
            anslist.Add("Seven Apps You Didn't Know That Can Enhance Your " + Keyword + ".")
            anslist.Add("5 Things Your Competitors Know About " + Keyword + ".")
            anslist.Add("Learning " + Keyword + " Is Not Difficult At All! You Just Need A Great Teacher!")
            anslist.Add("5 Secrets That Experts Of " + Keyword + " Don't Want You To Know.")
            anslist.Add("Ten Common Mistakes Everyone Makes In " + Keyword + ".")
            anslist.Add("Eliminate Your Fears And Doubts About " + Keyword + ".")
            anslist.Add("5 Reasons Why You Are A Rookie In " + Keyword + ".")
            anslist.Add("Enhance Your " + Keyword + " Skills During Your Lunch Break!")
            anslist.Add("10 " + Keyword + " That Will Actually Make Your Life Better.")
            anslist.Add("How " + Keyword + " Can Increase Your Profit!")
            anslist.Add("The History of " + Keyword + ".")
            anslist.Add("Reasons Why " + Keyword + " Is Getting More Popular In The Past Decade.")
            anslist.Add("Think You're An Expert In " + Keyword + "? Take This Quiz Now To Find Out.")
            anslist.Add("Seven Reasons Why People Like " + Keyword + ".")
            anslist.Add("Why Is Everyone Talking About " + Keyword + "?")
            anslist.Add("Ten Shocking Facts About " + Keyword + ".")
            anslist.Add("Seven Reasons Why You Shouldn't Rely On " + Keyword + " Anymore.")
            anslist.Add("15 Common Myths About " + Keyword + ".")
            anslist.Add("Now Is The Time For You To Know The Truth About " + Keyword + ".")
            anslist.Add("The 5 Common Stereotypes When It Comes To " + Keyword + ".")
            anslist.Add("7 Things You Didn't Know About " + Keyword + ".")
            anslist.Add("How To Master " + Keyword + " In Only 7 Days.")
            anslist.Add("Here's What No One Tells You About " + Keyword + ".")
            anslist.Add("5 Useful Tips From Experienced " + Keyword + " Practitioners.")
            anslist.Add("You Will Never Thought That Knowing " + Keyword + " Could Be So Beneficial!")
            anslist.Add("This Is Why This Year Will Be The Year Of " + Keyword + ".")
            anslist.Add("The Millionaire Guide On " + Keyword + " To Help You Get Rich.")
            anslist.Add("10 " + Keyword + " Mistakes You're Making Without Even Realizing It.")
            anslist.Add("Why It Is Not The Best Time To Pick Up " + Keyword + " Now.")
            anslist.Add("Why " + Keyword + " Had Been So Popular Till Now?")
            anslist.Add("How Learning " + Keyword + " Could Save Your Money And Time.")
            anslist.Add("Fully Utilize " + Keyword + " To Enhance Your Business.")
            anslist.Add("7 Preparations You Should Make Before Using " + Keyword + ".")
            anslist.Add("Ten Mind Numbing Facts About " + Keyword + ".")
            anslist.Add("The 5 Secrets About " + Keyword + " Only A Handful Of People Know.")
            anslist.Add("Understand " + Keyword + " Before You Regret.")
            anslist.Add("Seven " + Keyword + " Tips You Need To Learn Now.")
            anslist.Add("﻿How To Own " + Keyword + " For Free.")
            anslist.Add("Everything You Need To Know About " + Keyword + ".")
            anslist.Add("Ten Benefits Of " + Keyword + " That May Change Your Perspective.")
            anslist.Add("Seven Quick Tips To Mastering " + Keyword + ".")
            anslist.Add("7 Great Tips To Earn More With " + Keyword + ".")
            anslist.Add("Seven Various Ways To Do " + Keyword + ".")
            anslist.Add("Top 10 Trends In " + Keyword + " To Watch.")
            anslist.Add("" + Keyword + " Will Make You Tons Of Cash. Here's How!")
            anslist.Add("Most Effective Ways To Overcome " + Keyword + "'s Problem.")
            anslist.Add("Seven Tips To Avoid Failure In " + Keyword + ".")
            anslist.Add("Five Lessons I've Learned From " + Keyword + ".")
            anslist.Add("This Year Will Be The Year of " + Keyword + ".")
            anslist2.Add("15 Facts You Never Knew About " + Keyword + ".")
            anslist2.Add("10 Ways " + Keyword + " Can Improve Your Business.")
            anslist2.Add("5 Ways To Use " + Keyword + " To Your Advantage.")
            anslist2.Add("Ten Little Tricks To Achieve The Best Results In " + Keyword + ".")
            anslist2.Add("15 Things To Know About " + Keyword + ".")
            anslist2.Add("Back To Basics. The 3 Fundamentals That Everyone Always Forget About " + Keyword + ".")
            anslist2.Add("Why Is " + Keyword + " So Famous?")
            anslist2.Add("Simple Guidance For You In " + Keyword + ".")
            anslist2.Add("How " + Keyword + " Can Ease Your Pain.")
            anslist2.Add("" + Keyword + " Is Not Rocket Science! Learn Them Now!")
            anslist2.Add("5 Awesome Things You Can Learn From Studying " + Keyword + ".")
            anslist2.Add("Is " + Keyword + " Any Good? 5 Ways You Can Be Certain.")
            anslist2.Add("Why Learning " + Keyword + " Can Actually Improve Your Health Condition!")
            anslist2.Add("Never Underestimate The Influence Of " + Keyword + ".")
            anslist2.Add("Ten Reasons Why Everyone Is Learning " + Keyword + " These Days!")
            anslist2.Add("The 10 Steps Needed For Putting " + Keyword + " Into Action.")
            anslist2.Add("10 Things Nobody Told You About " + Keyword + ".")
            anslist2.Add("5 Ingenious Ways You Can Do With " + Keyword + ".")
            anslist2.Add("All You Need To Know About " + Keyword + ".")
            anslist2.Add("Five Explanation On Why " + Keyword + " Is Important.")
            anslist2.Add("10 Things You Probably Didn't Know About " + Keyword + ".")
            anslist2.Add("Five Reason Why You Should Consider Picking Up " + Keyword + ".")
            anslist2.Add("Make Your Parents Proud By Learning " + Keyword + ".")
            anslist2.Add("Five Gigantic Influences Of " + Keyword + ".")
            anslist2.Add("The Modern Rules Of " + Keyword + ".")
            anslist2.Add("7 Fundamental Rules You Can't Afford To Ignore When It Comes To " + Keyword + ".")
            anslist2.Add("10 Factors That Affect " + Keyword + "'s Longevity.")
            anslist2.Add("10 Things You Need To Know About " + Keyword + " Today.")
            anslist2.Add("15 Ways To Improve Your " + Keyword + " Skills.")
            anslist2.Add("10 Precious Tips To Help You Get Better At " + Keyword + ".")
            anslist2.Add("7 Most Popular Ways To " + Keyword + ".")
            anslist2.Add("You Will Never Think That Learning " + Keyword + " Could Be So Beneficial! But It Is!")
            anslist2.Add("Five Reasons Why You Cannot Learn " + Keyword + " Well.")
            anslist2.Add("How To " + Keyword + " Better In Less Time.")
            anslist2.Add("5 Reasons Why You Should Invest In " + Keyword + ".")
            anslist2.Add("Learning " + Keyword + " Can Be Disastrous If You Neglect These 10 Simple Rules.")
            anslist2.Add("Master The Skills Of " + Keyword + " And Be Successful.")
            anslist2.Add("Seven Ways To Have Fun Learning " + Keyword + ".")
            anslist2.Add("10 Ingenious Ideas For You To Explore With " + Keyword + ".")
            anslist2.Add("Master " + Keyword + " In Just A Few Hours!")
            anslist2.Add("Five Basic Tools You Will Need To Learn " + Keyword + ".")
            anslist2.Add("7 Things You Must Know Before Trying " + Keyword + ".")
            anslist2.Add("Ten Useful Tips From Experts In " + Keyword + ".")
            anslist2.Add("Learn From These Mistakes Before You Learn " + Keyword + ".")
            anslist2.Add("7 Reasons You Should Fall In Love With " + Keyword + ".")
            anslist2.Add("Learn All About " + Keyword + " From This Politician.")
            anslist2.Add("Introducing A Revolutionary Method To Master " + Keyword + ".")
            anslist3.Add("15 Unexpected Ways " + Keyword + " Can Make Your Life Better.")
            anslist3.Add("5 Easy Ways To Facilitate " + Keyword + ".")
            anslist3.Add("Ten Solid Evidences Learning " + Keyword + " Is Good For Your Career Advancement.")
            anslist3.Add("Five Ways To Learn " + Keyword + " Effectively.")
            anslist3.Add("Ten " + Keyword + " Ideas That Can Impress Your Friends.")
            anslist3.Add("What I Wish Everyone Knew About " + Keyword + ".")
            anslist3.Add("" + Keyword + " Will Be A Thing Of The Past And Here's Why.")
            anslist3.Add("" + Keyword + " Is A Great Way To Increase Your Profit!")
            anslist3.Add("7 Features Of " + Keyword + " That Make Everyone Love It.")
            anslist3.Add("15 Stupid Questions You Should Have Asked Before Starting " + Keyword + ".")
            anslist3.Add("10 Solid Evidences Why " + Keyword + " Is Bad For Your Career Development.")
            anslist3.Add("5 Difficult Things About " + Keyword + ".")
            anslist3.Add("5 Things You Should Know About " + Keyword + ".")
            anslist3.Add("Learn How To Make More Money With " + Keyword + ".")
            anslist3.Add("Five Important Facts That You Should Know About " + Keyword + ".")
            anslist3.Add("5 Advices That You Must Listen Before Studying " + Keyword + ".")
            anslist3.Add("Seven Lessons That Will Teach You All You Need To Know About " + Keyword + ".")
            anslist3.Add("How To Learn " + Keyword + " Without Losing Your Mind.")
            anslist3.Add("How To Master " + Keyword + " With The Best " + Keyword + " Tips In Pictures.")
            anslist3.Add("How To Get People To Like " + Keyword + ".")
            anslist3.Add("Here's What People Are Saying About " + Keyword + ".")
            anslist3.Add("The Truth About " + Keyword + " Is About To Be Revealed.")
            anslist3.Add("Things That Make You Love And Hate " + Keyword + ".")
            anslist3.Add("Ten Must Know Tips If You Want To Avoid Failure In " + Keyword + ".")
            anslist3.Add("How You Know You're Doing " + Keyword + " The Right Way.")
            anslist3.Add("Are You Ready For " + Keyword + "? Take This Quick Quiz To Find Out!")
            anslist3.Add("Learning " + Keyword + " Can Be Addictive. Here's How You Can Get Yourself Hooked.")
            anslist3.Add("10 Advantages Of " + Keyword + " And How You Can Make Full Use Of It.")
            anslist3.Add("7 Things You Most Likely Didn't Know About " + Keyword + ".")
            anslist3.Add("The Rank Of " + Keyword + " In Consumer's Market.")
            anslist3.Add("Ten Common Misconceptions About " + Keyword + ".")
            anslist3.Add("7 Easy Rules Of " + Keyword + ".")
            anslist3.Add("7 Unbelievable Facts About " + Keyword + ".")
            anslist3.Add("Five " + Keyword + " Tips From " + Keyword + " Experts.")
            anslist3.Add("How To Learn About " + Keyword + " In Only 10 Days.")
            anslist3.Add("The Billionaire Guide On " + Keyword + " That Will Get You Rich.")
            anslist3.Add("Ten New Thoughts About " + Keyword + " That Will Turn Your World Upside Down.")
            anslist3.Add("10 Things That Matter When You Are Learning " + Keyword + ".")
            anslist3.Add("10 Doubts About " + Keyword + " You Should Clarify.")
            anslist3.Add("Eliminate Your Fear And Pick Up " + Keyword + " Today.")
            anslist3.Add("Top Ten Sites You Can Learn " + Keyword + " For Free!")
            anslist3.Add("Ten Reasons Why You Shouldn't Learn " + Keyword + " On Your Own.")
            anslist3.Add("Five Inconvenient Truth Why You Can't Master " + Keyword + ".")
            anslist3.Add("15 Unconventional Knowledge About " + Keyword + " That You Can't Learn From Books.")
            anslist3.Add("7 Innovative Approaches To Improve Your " + Keyword + ".")
            anslist3.Add("15 Top Reasons Why You Face Obstacles In Learning " + Keyword + ".")
            anslist3.Add("The Most Unconventional Ways to Learn " + Keyword + ".")
            anslist3.Add("15 Advices That You Must Listen To Before Learning " + Keyword + ".")
            anslist3.Add("5 Quick Tips For " + Keyword + ".")
            anslist3.Add("What You Know About " + Keyword + " And What You Don't Know About " + Keyword + ".")
            anslist4.Add("How " + Keyword + " Is Going To Change Your Business Strategies.")
            anslist4.Add("This Is Why You Face Obstacles In Learning " + Keyword + ".")
            anslist4.Add("5 Simple (But Important) Things To Remember About " + Keyword + ".")
            anslist4.Add("The Ten Reasons Tourists Love " + Keyword + ".")
            Dim rnd As New Random
            Dim rndNum As Integer = rnd.Next(50)
            Dim rnd2 As New Random
            Dim rndNum2 As Integer = rnd2.Next(50)
            Dim rnd3 As New Random
            Dim rndNum3 As Integer = rnd3.Next(50)
            Dim rnd4 As New Random
            Dim rndNum4 As Integer = rnd4.Next(4)
            FlatTextBox1.Text = anslist(rndNum)
            FlatTextBox2.Text = anslist2(rndNum2)
            FlatTextBox5.Text = anslist3(rndNum3)
            FlatTextBox6.Text = anslist4(rndNum4)
        End If
    End Sub

    Private Sub GroupBox1_Enter(sender As Object, e As EventArgs) Handles GroupBox1.Enter

    End Sub

    Private Sub FlatButton3_Click(sender As Object, e As EventArgs) Handles FlatButton3.Click
        Clipboard.SetText(FlatTextBox1.Text)
    End Sub

    Private Sub FlatButton4_Click(sender As Object, e As EventArgs) Handles FlatButton4.Click
        Clipboard.SetText(FlatTextBox2.Text)
    End Sub

    Private Sub FlatButton5_Click(sender As Object, e As EventArgs) Handles FlatButton5.Click
        Clipboard.SetText(FlatTextBox5.Text)
    End Sub

    Private Sub FlatButton6_Click(sender As Object, e As EventArgs) Handles FlatButton6.Click
        Clipboard.SetText(FlatTextBox6.Text)
    End Sub

    Private Sub Form24_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        FlatComboBox1.Items.Add("Is a generic term")
        FlatComboBox1.Items.Add("Is a brand/product")
        FlatComboBox1.Items.Add("Is an event")
        FlatComboBox1.Items.Add("Is an industry")
        FlatComboBox1.Items.Add("Is a location")
        FlatComboBox1.Items.Add("Is a person's name")
        FlatComboBox1.Items.Add("Is a skill")
    End Sub
End Class